logbook.strategy=without-body
logging.level.am.ik.mcp.fetch.FetchServerApplication=debug
server.port=${PORT:8090}
spring.ai.mcp.server.name=fetch-server
spring.ai.mcp.server.protocol=STREAMABLE
spring.application.name=fetch-server
spring.threads.virtual.enabled=true
