logbook.strategy=without-body
logging.level.am.ik.mcp.fetch.FetchServerApplication=debug
management.logging.export.enabled=false
management.opentelemetry.instrumentation.logback-appender.capture-experimental-attributes=true
management.opentelemetry.instrumentation.logback-appender.capture-key-value-pair-attributes=true
management.opentelemetry.logging.export.otlp.compression=gzip
management.otlp.metrics.export.enabled=false
management.tracing.export.enabled=false
management.tracing.sampling.probability=1.0
server.port=${PORT:8090}
spring.ai.mcp.server.name=fetch-server
spring.ai.mcp.server.protocol=STREAMABLE
spring.application.name=fetch-server
spring.threads.virtual.enabled=true
